### DISCUSSION TITLE
Error Loading SSH Key

### DISCUSSION THREAD

**Discussion by sauld95** [AndreasAugustin/actions-template-sync#543] [Q&A] [answered]
I'm not too familiar with how Github actions, tokens or ssh keys really work and I feel that I'm possibly inputting the wrong information.

I'm receiving an error on this step.
Source repo path I have it set in this format: username/repository
```
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: ${{ secrets.SOURCE_REPO_PATH }}
          source_repo_ssh_private_key: ${{ secrets.SOURCE_REPO_SSH_PRIVATE_KEY }}
```
 ```
59 Load key "/tmp/.ssh/id_rsa_actions_template_sync": error in libcrypto
60 git@github.com: Permission denied (publickey).
61 fatal: Could not read from remote repository.
62
63 Please make sure you have the correct access rights
64 and the repository exists.
65 fatal: Needed a single revision
66 Error: Process completed with exit code 128.
```

I'm not sure why I'm being denied. I set the repository secret to the ssh private key and added the ssh public key to the deploy keys in the template repository
