### DISCUSSION TITLE
` nothing to commit` during `commit changes` log step in github actions

### DISCUSSION THREAD

**Discussion by syntapy** [AndreasAugustin/actions-template-sync#590] [Q&A] [answered]
Hi, not sure where to proceed in terms of fixing this

I am trying to use a template repository with a repository that is derived from that. In my derivetive repository I add a test comment in a script file I use and try to sync the derivetive repository to that

I've managed to get the manually run template sync workflow to run without errors in my derivetive repo, but it says `nothing to commit` at the end, and no branch or PR is made in my derivetive reposirory

I have verified that it is checking out the correct template repository, based on looking at commit hash, and it is trying

From my template repo I have in `.github/workflows/template-sync.yml`: 

```
on:
  # cronjob trigger
  schedule:
    - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: write
      pull-requests: write

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
        # https://github.com/actions/checkout#usage
        # uncomment if you use submodules within the repository
        # with:
        #   submodules: true

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: syntapy/test-driven-web-app-template
          upstream_branch: main
          steps: "commit,push,pr"
          pr_labels: template_sync
```

This is matched in my derivetive repo (which I manually did)

In a script in `bin/` I then add a test comment. Then I run the workflow. I verify that it checks out from the correct derivetive repo based on the hash in the Checkout step. And the hash in the actions-template-sync step shows the correct template repo

But in the workflow run log, when it gets to the `commit changes` part, it says

```
  ::info::handle .templatesyncignore
  ::info::nothing to commit
```

My template repo is [test-driven-web-app-template](https://github.com/syntapy/test-driven-web-app-template) and here is [the log for the workflow run in my derivetive repo](https://github.com/syntapy/1-react-quickstart/actions/runs/12470971562/job/34807341733#step:3:351)

--------
`The sciences and arts, all inventions, crafts, trades and their products have come forth from the intellect of man. It is evident that within the human organism the intellect occupies the supreme station.`
