### ISSUE TITLE
Keep getting host key verification failed.

### ISSUE THREAD

**Issue by Daniel-Boll** [AndreasAugustin/actions-template-sync#110]
**Describe the bug**
I keep getting the `Host key verification failed.` error message on SSH connection no matter what I do. I've already tried my own SSH key which has more access privileges than it's even required, yet still no success.  

**Expected behavior**
- [ ] Generate a new SSH Key pair (OpenSSH format)
- [ ] Get the public key and set it as the Deploy Key on the private template repo
- [ ] Get the private key and  set it as a secret in the "`child`" repo
- [ ] Set both repo path and target branch in the "`child's`" repo secrets
- [ ] Run the action and expect for the best.

**Logs**

```
 + echo '::debug::We are using SSH within a private source repo'
+ mkdir -p /tmp/.ssh
git init
+++ awk '{print $1}'
+++ git ls-remote git@github.com:*** HEAD
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
++ TEMPLATE_REMOTE_GIT_HASH=
+++ git rev-parse --short ''
fatal: Needed a single revision
++ NEW_TEMPLATE_GIT_HASH=
```

**yml file**

```yml
name: sync-repo-with-core

on:
  # Every minute
  # TODO: change this later...
  schedule:
  - cron:  "* * * * *"
  # manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    environment: Development
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.1.5-draft
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: ${{ secrets.SOURCE_REPO_PATH }}
          upstream_branch: ${{ secrets.TARGET_BRANCH }} # defaults to main
          source_repo_ssh_private_key: ${{ secrets.SOURCE_REPO_SSH_PRIVATE_KEY }} # contains the private ssh key of the private repository
```

I have no clue what I'm doing wrong. Thank you for your assistance in this matter,

Daniel Boll
