### ISSUE TITLE
action-template-sync failing

### ISSUE THREAD

**Issue by fabriziocacicia** [AndreasAugustin/actions-template-sync#168]
**Describe the bug**
To describe the bug I'm reporting the logs of the Action:
```
+++ git ls-remote ***github.com/fabriziocacicia/template_base HEAD
+++ awk '{print $1}'
++ TEMPLATE_REMOTE_GIT_HASH=28ad6a0acfbf[39](https://github.com/fabriziocacicia/template_base_dart/runs/6035601769?check_suite_focus=true#step:4:39)f4f0fd0a9fed54eb9de43b5581
+++ git rev-parse --short 28ad6a0acfbf39f4f0fd0a9fed54eb9de43b5581
fatal: unsafe repository ('/github/workspace' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
++ NEW_TEMPLATE_GIT_HASH=
```

**To Reproduce**
Just manually running the Action configured with this [yaml file](https://github.com/fabriziocacicia/template_base_dart/blob/e0ed9e9cfb302b991d2e0fe4d2203fe376058fba/.github/workflows/template_base_sync.yml)

 **Possible solution**
I think https://github.com/actions/checkout/issues/766 could be a possible cause, and this https://github.com/rht/zulip-archive/commit/2957a945a185b8fadc20b484fde55256e42717d5 a possible solution

**Comment by AndreasAugustin** [comment]
Hi @fabriziocacicia thanks for the bug report.
I will have a look into it within the next days.

**Comment by AndreasAugustin** [comment]
Was able to reproduce the issue within one of my repositories.

Thanks @fabriziocacicia  for the links and hints:
> **Possible solution**
> I think [actions/checkout#766](https://github.com/actions/checkout/issues/766) could be a possible cause, and this [rht/zulip-archive@2957a94](https://github.com/rht/zulip-archive/commit/2957a945a185b8fadc20b484fde55256e42717d5) a possible solution

The reason should be (as mentioned in your link) a currently released git sec bump https://github.blog/2022-04-12-git-security-vulnerability-announced/

Need to check how to solve it in a nice way.

**Comment by AndreasAugustin** [comment]
@all-contributors please add @fabriziocacicia  for security and bug

**Comment by AndreasAugustin** [comment]
@fabriziocacicia thanks for the report. The issue is solved. I do not like the solution but it works :+1: 

please upgrade the `actions-template-sync` to latest version `v0.3.1-draft`. Furthermore please also update the `checkout` to `v3` to reduce the risk of failing checkout.

```yaml
on:
  # daily trigger
  schedule:
  - cron:  "0 0 * * *"
  # manual trigger
  workflow_dispatch:
jobs:
  template_base_sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3  # update to v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.3.1-draft  # update to v0.3.1-draft
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: fabriziocacicia/template_base
          upstream_branch: main 
          pr_labels: template-update # defaults to chore,template-sync
```
