### ISSUE TITLE
Issue with accessing private repo template

### ISSUE THREAD

**Issue by mikematos84** [AndreasAugustin/actions-template-sync#200]
I am attempting to use this action to sync from a private repo template I have set up. I created a new set of keys for the repo itself. I have the `public key` setup under `deploy keys` in the private repo template, and the `private key` setup as the `SOURCE_REPO_SSH_PRIVATE_KEY` secret within the repo that I want to sync with the template. I also have `<owner/repo>` name setup in the `SOURCE_REPO_PATH` secret as well. Whenever I run the task, I get the following error:

```bash
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Looking over everything, I believe I have all the correct access rights since I own both repos, and the template exists. So I am unsure what the issue may be. 

Any help would be greatly appreciated. 

PS: Running 0.4.1-draft

**Comment by AndreasAugustin** [comment]
Hi @mikematos84 . Thanks for the issue. I will start investigating ASAP.

**Comment by AndreasAugustin** [comment]
@mikematos84 I just made a test run with a private repository and your listed version v0.4.1-draft.
On my side everything is working.

Due to your error message I guess there are some possible reasons:

- Is there a chance that you forgot to add the configuration line into the .workflow/<action>.yml file which contains the name of your github secret? (you can choose the name on your own). https://github.com/AndreasAugustin/actions-template-sync#ssh

```yaml
 with:
          ...
          source_repo_ssh_private_key: ${{ secrets.<add here the name of the secret> }} # contains the private ssh key of the private repository
```

- The <owner/repo> is not properly setup (you already mentioned that it is not the case)
- The public private keys are not from same pair (you can create new keypair with `ssh-keygen`)
- You need to add the public key into the source repo (template) as deployment key and the private as secret in your target repo (you already statet that this is not the case)

**Comment by mikematos84** [comment]
Thanks for your response. So just for transparency, this is currently my `template-sync.yaml` within my `target` directory. 

```yaml
# https://github.com/marketplace/actions/actions-template-sync
name: Template Sync

on:
  # cronjob trigger
  schedule:
    - cron: '0 0 1 * *'
  # manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.4.1-draft
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: ${{ secrets.SOURCE_REPO_PATH }}
          source_repo_ssh_private_key: ${{ secrets.SOURCE_REPO_SSH_PRIVATE_KEY }}
```
So I beleive I have the template setup correctly. Also I have the public key set as a deploy key in the `source` depo and and the private key as a secret in the `target`.  Also I created a specific ssh-key pair for the repo so that I am not using my ssh key for global access to my GitHub account itself. 

```yaml
next-github-pages-app # private source repo, template. contains public key as deploy key
next-test-app # public target repo, contains private key as secret. contains `template-sync.yml` action to trigger
```

There has to be something I am doing wrong but I can't put my finger on it. 

I will try to debug locally using the ssh-key pair I created specifically for the repo.
