### ISSUE TITLE
Use `gh auth` for general authentication 

### ISSUE THREAD

**Issue by msiebeneicher** [AndreasAugustin/actions-template-sync#238]
**Is your feature request related to a problem? Please describe.**
We are running on a github enterprise instance and mirrored this action. Because of global blocked ssh ports we are not able to use the `source_repo_ssh_private_key` and are using separate github apps for this kind of access. 

**Describe the solution you'd like**
Usage of `gh auth login` and `gh auth git-credential` to handle the authentication to create the final PR

**Describe alternatives you've considered**
n.a.

**Comment by AndreasAugustin** [comment]
@msiebeneicher thanks for the issue. I think this should also sole #97 what I wanted to implement some times ago :) using GitHub apps is also a nice idea.

**Comment by msiebeneicher** [comment]
@AndreasAugustin : here an example config how you can use a github app:

```yml
on:
    # cronjob trigger
  schedule:
  - cron:  "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
     - name: Generate token # see: https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
        
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.5.0-draft
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          source_repo_path: <owner/repo>
          upstream_branch: <target_branch> # defaults to main
          pr_labels: <label1>,<label2>[,...] # optional, no default
```
