### ISSUE TITLE
[Question] Sync from template in a private repo

### ISSUE THREAD

**Issue by george-gca** [AndreasAugustin/actions-template-sync#299]
Not sure if this is a documentation bug. When using this action in a private repo created from a template, in the docs there is the option to use [another github app](https://github.com/AndreasAugustin/actions-template-sync#using-github-app) to provide the key. With it, is it still necessary to do the ssh part, create key, etc?

**Comment by AndreasAugustin** [comment]
Hi @george-gca and thank you for the question.
If you use a github app, you do not need to add an additional ssh key.
Within the documentation there are 2 parts

- github app
- ssh key

both parts are on the same level so it is thought to be read as an `or`.
I will think about how to make it more clear.

**Comment by AndreasAugustin** [comment]
Do you have the app id added to your github repo action secrets?

**Comment by george-gca** [comment]
No, I thought everything that I needed was already set. This is not well documented in the [github app token](https://github.com/tibdex/github-app-token), or anywhere that I could find actually. How do I find and configure this?

I am doing this to keep my personal site updated with the [template repo](https://github.com/george-gca/multi-language-al-folio).

**Comment by AndreasAugustin** [comment]
Maybe that link helps https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md

Just the first 2 sections about create and consume are important.

It was a fast google, not sure if all is fine, but looks okish.

The app Id and the app secret you get when you create the GitHub app

**Comment by george-gca** [comment]
> The app Id and the app secret you get when you create the GitHub app

I don't think I get it. By creating the app you mean by creating the yml file in the `.github/workflows`? Where can I find this app id and app secret?

The only app that is currently displayed installed in my repo is the giscus app, to allow comments in the posts.

**Comment by AndreasAugustin** [comment]
Your mentioned yaml file is not a GitHub app. It is workflow definition file. A GitHub app is needed to handle permissions to a GitHub repo. You do not need such an app when you have for example a public repository or if you use other AUTH related techniques like ssh.

For private source repos it is possible to use a GitHub app. But first you need to create one. Plus check the docs here 
https://github.com/AndreasAugustin/actions-template-sync#using-github-app

**Comment by george-gca** [comment]
Ah, now I get it. I thought that every step I needed was already included in the README.

Seemingly, creating a simple Github App is not that easy though. I just got engulfed in a sea of links.
Found [this documentation](https://docs.github.com/en/developers/apps/building-github-apps), and [this github app](https://github.com/marketplace/actions/use-app-token) that states:

> Do not have a Github App? Get a quick start with [probot](https://probot.github.io/).

And it just keeps getting overwhelming. But I can't turn my site repo open, since it has some information like google analytics id. Maybe one day I will take some time to configure it correctly, but for now I will keep doing it manually.

Thanks for the help o/.

**Comment by AndreasAugustin** [comment]
Ist your site repo the target or the source repo to sync? The target repo can be private without GitHub app or ssh. 

If the source repo need to be private, maybe use the ssh way? It is maybe a bit simpler. Step by step guide (as mentioned above): https://dev.to/andreasaugustin/github-actions-template-sync-1g9k

**Comment by george-gca** [comment]
The [template](https://github.com/george-gca/multi-language-al-folio) (`source`) is public, my site (`target`) is not. I wanted to update my site with the latest updates from the template.

Reverted my workflow to [the first one in your README](https://github.com/AndreasAugustin/actions-template-sync#github-actions). Being more clear, my workflow in the `target` now looks like this:

```yml
name: Sync from template
on:
  # cronjob trigger
  schedule:
  - cron:  "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.7.0-draft
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: george-gca/multi-language-al-folio
          upstream_branch: main
```

And I am getting this error:

```
push changes and create PR
  ++ debug 'push changes'
  ++ echo '::debug::push changes'
  ++ git push --set-upstream origin chore/template_sync_d57ce6d
  To XXXXXXXXXXXXX
   ! [remote rejected] chore/template_sync_d57ce6d -> chore/template_sync_d57ce6d (refusing to allow a GitHub App to create or update workflow `.github/workflows/deploy-image.yml` without `workflows` permission)
  error: failed to push some refs to 'XXXXXXXXXXXXXXXXX'
```

But in my `target` settings the Workflow permissions are already set to read/write:

---

![image](https://user-images.githubusercontent.com/31376482/218138959-f6d4013d-39f7-403e-906a-9a4d93af77ff.png)

---

From what I understood, the `${{ secrets.GITHUB_TOKEN }}` is something that I don't need to create, right? It is something internal to github?
