### ISSUE TITLE
[Feat]: file deletion

### ISSUE THREAD

**Issue by aairey** [AndreasAugustin/actions-template-sync#401]
### Describe the feature

Support deleting files that were previously managed, now template-sync leaves the prior fil in place.

### Use Case

Moved from `.releaserc.json` to `.releaserc.yaml`, the `.releaserc.json` stays in place but we want to remove it.

### Proposed Solution

Optional delete option on the action?
Or delete by default (breaking change perhaps).

### Acknowledgements

- [ ] I may be able to implement this feature request

**Comment by thatryan-di** [comment]
I came to ask this same question. Just getting this set up and during testing I added a file called `dummy.txt ` to my source repo then sync my target repo and it pulled in the new file. Awesome! 
I then went back to source/template repo and deleted that `dummy.txt ` file and then synced again but the test file did not get deleted from the repo.

**Comment by AndreasAugustin** [comment]
Hi @thatryan-di and thank you for your investigation. 

Will have a closer look into the issue soon.

**Comment by AndreasAugustin** [comment]
Hi @aairey  and @thatryan-di . Sorry for late answer.
I was able to reproduce the issue and track it down.

As a default pull command

`git pull --allow-unrelated-histories --squash --strategy=recursive -X theirs <remote_repo>`  is used. It seems that the `--squash` is the responsible part.
Removing that option should solve your issue. So far it is possible with the [git_remote_pull_params](https://github.com/AndreasAugustin/actions-template-sync#configuration-parameters) config parameter.
Removing the `--squash`  should do the trick (possible after 2nd run).

I will think about removing `--squash` from the default and let the user decide at merge time if squash should be used.

**Comment by AndreasAugustin** [comment]
Hi @aairey and @thatryan-di . Sorry for letting you wait. The issue is not super straight forward to solve.
The idea is currently to add the suggestion of @aairey (parameter to allow deletion) in combination with removing the squash option (out of convenience reasons).

The command `git log --diff-filter D --pretty="format:" --name-only <source_revision>..HEAD | sed '/^$/d' ` should reveal the deleted files. With the knowledge of the deleted files within the base repository the actual deletion will be the easy part ;)

Need to do some final testing and the implementation also need to be done.

**Comment by AndreasAugustin** [comment]
Hi @aairey  and @thatryan-di .
Sorry this task is taking some time... Somehow it is not trivial and unfortunately currently my free time is limited.

I somehow have a solution. You can try it with

```yaml
name: actions-template-sync

on:
  # cronjob trigger At 00:00 on day-of-month 1. https://crontab.guru/every-month
  schedule:
    - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@file_deletion
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: AndreasAugustin/template-test
          upstream_branch: main # defaults to main
          # git_remote_pull_params: --allow-unrelated-histories --strategy=recursive -X theirs --squash
          git_remote_pull_params: --allow-unrelated-histories --strategy=recursive --no-edit
          is_force_deletion: true
``` 

Please be aware that the `git_remote_pull_params` are important. The related changes: #435 
Within my tests it is deleting the files. I did not find a solution so far which is working with all pull commands.

Maybe you find some time to do some tests. Thanks :rocket:
