### ISSUE TITLE
[Bug]: allow submodules

### ISSUE THREAD

**Issue by centifanto** [AndreasAugustin/actions-template-sync#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This action is exactly what I was looking for, thank you. I am using a Jekyll template repo, and wanted to use your action to keep my repo up to date

However, this template has a submodule for some of it's static assets --> https://github.com/cotes2020/chirpy-starter/tree/main/assets

I ran into this error:
`error: 'assets/lib' does not have a commit checked out`

So I decided to just remove (with `rm -rf `) my repo's copy since it would be subsequently updated with the pull form remote

Upon removing, it seemed like solved the issue. But then this error popped up:
`Could not access submodule 'assets/lib'`

### Expected Behavior

The action to allow pulling submodules from the remote

### Current Behavior

It fails when trying to pull the submodule, either because it has `.git` information, or when removing it can't fetch that remote module.

### Template sync version Version

1.1.3

**Comment by AndreasAugustin** [comment]
Hi @centifanto and thank you for the issue.
I had a short look into your public repo.
So far this action does not support git submodules (yet).

As a fast workaround you could try the following:
For checking out the source code you use [actions/checkout@v3](https://github.com/actions/checkout) action.
The action has an option to checkout submodules

```yaml

    # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
    # recursively checkout submodules.
    #
    # When the `ssh-key` input is not provided, SSH URLs beginning with
    # `git@github.com:` are converted to HTTPS.
    #
    # Default: false
    submodules: ''
```
So instead of doing the `rm -rf` like mentioined above you could try to change the action to

```yaml
on:
    # cronjob trigger
  # schedule:
  # - cron:  "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      # - name: remove submodule
      # run: |
      #    rm -rf assets/lib
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: cotes2020/chirpy-starter
          git_remote_pull_params: --allow-unrelated-histories --squash --strategy=recursive
```

theoretically this should do the trick :)
