### ISSUE TITLE
[Bug]: Labels with emoji and space are not supported

### ISSUE THREAD

**Issue by kdeldycke** [AndreasAugustin/actions-template-sync#461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi have a step that looks like this:
```yaml
      - uses: AndreasAugustin/actions-template-sync@v1.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: kdeldycke/awesome-template
          pr_title: "[sync] Template"
          pr_commit_msg: "[sync] Template"
          pr_labels: 📚 documentation
```
([source](https://github.com/kdeldycke/workflows/blob/a112378606328c4905de57ae090b93a61f455a07/.github/workflows/docs.yaml#L381-L389))

This fails because the label contains emoji.

### Expected Behavior

I would like `actions-template-sync` to be able to label PRs it creates with labels containing emojis and spaces.

### Current Behavior

With the YAML configured as above with emoji, the action ends up with this issue:
```text
git init
::info::Missing env variable 'UPSTREAM_BRANCH' setting to remote default main
::info::current git hash: 50898d2f59a096aa29e64c1cdef9fd680bd0e113
Check new changes
Pull template
commit changes
cleanup older PRs
check for missing labels
  HTTP 422: Validation Failed (https://api.github.com/repos/kdeldycke/awesome-engineering-team-management/labels)
  name must contain more than native emoji
```

### Template sync version Version

1.6.0
