### ISSUE TITLE
[Feat]: enable partially execution of the action

### ISSUE THREAD

**Issue by AndreasAugustin** [AndreasAugustin/actions-template-sync#478]
### Describe the feature

Would be nice to have the possibility to only execute some partial steps within the action.

e.g.

```yaml
 - name: Test action step
        uses: AndreasAugustin/actions-template-sync@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: AndreasAugustin/template.git
          steps: pull,commit  # define the steps to execute
```

With this people are able to use different actions with the current workflow steps

### Use Case

Sometimes people want to be able to have some actions, commands executed in between the step (e.g. discussion #467, or https://github.com/cookiecutter/cookiecutter).
With the possibility of the split something like

```yaml
- name: Test action step
      uses: AndreasAugustin/actions-template-sync@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_repo_path: AndreasAugustin/template.git
        steps: pull  # define the steps to execute
- name: step in between
  run: sed -i "s/foo/\/bar/g" "*.md" \;
- name: Test action step
    uses: AndreasAugustin/actions-template-sync@v1
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      source_repo_path: AndreasAugustin/template.git
      steps: commit,push,pr  # define the steps to execute
```

would be possible.

The difference to the hooks would be that the people would also be able to use other github actions in between.
(currently possible with hooks e.g. use exit 0 in hook, but not super convenient. :ninja: )

### Acknowledgements

- [X] I may be able to implement this feature request
