### ISSUE TITLE
[Bug]: `could not open '.git/COMMIT_EDITMSG': Permission denied`

### ISSUE THREAD

**Issue by kdeldycke** [AndreasAugustin/actions-template-sync#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Re-checking out the PR created by `actions-template-sync` works but doesn't allow for pushing back to the PR because of permission issues.

### Expected Behavior

I'm surprised there is an issue with file permissions as I am not messing anytime with users on the file system. Is this an edge-case that's introduced by `actions-template-sync`?

### Current Behavior

The [following workflow](https://github.com/kdeldycke/awesome-billing/blob/1884788d20774e746b33d398e11f656084820a6d/.github/workflows/docs.yaml#L28-L79):
```yaml
  awesome-template-sync:
    name: Sync awesome template
    if: >
      startsWith(github.event.repository.name, 'awesome-')
      && github.event.repository.name != 'awesome-template'
    runs-on: ubuntu-22.04
    # We need custom PAT through the whole job so we get workflow permissions to update all the boilerplate .github
    # files from awesome-template.
    steps:

      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_UPDATE_GITHUB_PAT || secrets.GITHUB_TOKEN }}

      - name: Sync from template repo
        id: template_sync
        uses: AndreasAugustin/actions-template-sync@v1.8.1
        with:
          github_token: ${{ secrets.WORKFLOW_UPDATE_GITHUB_PAT || secrets.GITHUB_TOKEN }}
          source_repo_path: kdeldycke/awesome-template
          pr_title: "[sync] Updates from `awesome-template` repository"
          pr_commit_msg: "[sync] Updates from `awesome-template` repository"
          pr_branch_name_prefix: "sync-awesome-template"
          pr_labels: "📚 documentation"

      - name: Checkout template sync PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ steps.template_sync.outputs.pr_branch }}
          token: ${{ secrets.WORKFLOW_UPDATE_GITHUB_PAT || secrets.GITHUB_TOKEN }}


      - name: Update repo URLs
        # Replace "/kdeldycke/awesome-template/" in URLs by "/kdeldycke/awesome-<repo_id>/".
        run: >
          find ./.github/ -type f -iregex '.*\.\(md\|yaml\)$' -print -exec sed -i
          "s/\/kdeldycke\/awesome-template\//\/kdeldycke\/${{ github.event.repository.name }}\//g" "{}" \;

      - uses: peter-evans/create-pull-request@v6.0.1
        with:
          token: ${{ secrets.WORKFLOW_UPDATE_GITHUB_PAT || secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
          commit-message: "[sync] Updates from `awesome-template`"
          title: "[sync] Updates from `awesome-template`"
          body: >
            <details><summary><code>Workflow metadata</code></summary>
            > [Auto-generated on run `#${{ github.run_id }}`](${{ github.event.repository.html_url }}/actions/runs/${{
            github.run_id }}) by `${{ github.job }}` job from [`docs.yaml`](${{ github.event.repository.html_url
            }}/blob/${{ github.sha }}/.github/workflows/docs.yaml) workflow.
            </details>
          branch: ${{ needs.awesome-template-sync.outputs.pr_branch }}

```

Ends up with this error at the `create-pull-request` step:

![Screenshot 2024-03-03 at 17 05 07](https://github.com/AndreasAugustin/actions-template-sync/assets/159718/7c57a10b-d403-4062-bbde-cdc1c437f6c4)

See the source of the workflow run at: https://github.com/kdeldycke/awesome-billing/actions/runs/8130308519/job/22218375401#step:10:71

### Template sync version Version

1.8.1
