### ISSUE TITLE
[Bug]: `Remote "origin" does not support the Git LFS locking API`

### ISSUE THREAD

**Issue by kdeldycke** [AndreasAugustin/actions-template-sync#485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While searching for a workaround for #467, I was unable to continue working on the branch produced by `actions-template-sync` because of LFS.

### Expected Behavior

I expect LFS to be not be activated by default for repository not configured for it.

### Current Behavior

The following job:
```yaml
  awesome-template-sync:
    name: Sync awesome template
    if: >
      startsWith(github.event.repository.name, 'awesome-')
      && github.event.repository.name != 'awesome-template'
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4.1.1
        with:
          # We need custom PAT with workflows permissions so we can update all the boilerplate .github files from
          # awesome-template.
          token: ${{ secrets.WORKFLOW_UPDATE_GITHUB_PAT || secrets.GITHUB_TOKEN }}

      - name: Sync from template repo
        id: template_sync
        uses: AndreasAugustin/actions-template-sync@v1.8.1
        with:
          # We need custom PAT with workflows permissions so we can update all the boilerplate .github files from
          # awesome-template.
          github_token: ${{ secrets.WORKFLOW_UPDATE_GITHUB_PAT || secrets.GITHUB_TOKEN }}
          source_repo_path: kdeldycke/awesome-template
          pr_title: "[sync] Updates from `awesome-template` repository"
          pr_commit_msg: "[sync] Updates from `awesome-template` repository"
          pr_branch_name_prefix: "sync-awesome-template"
          pr_labels: "📚 documentation"
          is_pr_cleanup: true

      - name: Print PR branch ID
        run: |
          echo "PR branch ID: ${{ steps.template_sync.outputs.pr_branch }}"

      - name: Checkout template sync PR
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ steps.template_sync.outputs.pr_branch }}
          # We need custom PAT with workflows permissions so we can update all the boilerplate .github files from
          # awesome-template.
          token: ${{ secrets.WORKFLOW_UPDATE_GITHUB_PAT || secrets.GITHUB_TOKEN }}

      - name: List commits
        run: |
          git log

      - name: Update repo URLs
        # Replace "/kdeldycke/awesome-template/" in URLs by "/kdeldycke/awesome-<repo_id>/".
        run: >
          find ./.github/ -type f -iregex '.*\.\(md\|yaml\)$' -print -exec sed -i
          "s/\/kdeldycke\/awesome-template\//\/kdeldycke\/${{ github.event.repository.name }}\//g" "{}" \;

      - name: Show diff
        run: |
          git diff

      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Show diff
        run: |
          git commit --all -m 'Update URLs'

      - run: >
          git push
```

Ends up with the following error at the last `git push` step:
![Screenshot 2024-03-04 at 15 03 11](https://github.com/AndreasAugustin/actions-template-sync/assets/159718/20d32200-d411-493b-b383-df5dcff9741c)

Log of the workflow run is available at: https://github.com/kdeldycke/awesome-billing/actions/runs/8123005442/job/22202990790

### Possible Solution

A quick fix in my case was to hack the local git configuration with a dedicated step:
```yaml
      - name: Deactivate LFS
        run: |
          git config lfs.https://github.com/kdeldycke/${{ github.event.repository.name }}.git/info/lfs.locksverify false
```

### Additional Information/Context

LFS support was introduced in:
- https://github.com/AndreasAugustin/actions-template-sync/commit/5335a55
- https://github.com/AndreasAugustin/actions-template-sync/issues/273

### Template sync version Version

1.8.1

**Comment by AndreasAugustin** [comment]
Hi @kdeldycke and thanks for the report.
Hmm actually back in time I was thinking about using a input parameter for enabling git lfs. Thought there is no issue doing per default. Seems I was wrong on that :ninja: 

I do not fully understand the issue because github is supporting git lfs (at least the public one, not sure if every enterprise server is supporting git lfs)

**Remark**
Actually not an issue related to git lfs, but possibly solvable:
you are also using a step 

```yaml
      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
```

possibly removing `--global` within [src/entrypoint.sh](https://github.com/AndreasAugustin/actions-template-sync/blob/main/src/entrypoint.sh) line 75++ is a better option. I  need to think about the solution and possibly check other famous github actions how they are doing the configuration.

```bash
  git config --global user.email "${GIT_USER_EMAIL}"
  git config --global user.name "${GIT_USER_NAME}"
  git config --global pull.rebase false
  git config --global --add safe.directory /github/workspace
  git lfs install
```
