### ISSUE TITLE
[Bug]: when cleaning up PRs with is_pr_cleanup: true, switches to main on PR cleanup

### ISSUE THREAD

**Issue by kanno41** [AndreasAugustin/actions-template-sync#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I had an old PR existing and tried to have it clean up the old PR. However, when it cleaned up the PR, it switched the branch to main. I am using a GitHub App.
<img width="787" alt="template-sync-bug" src="https://github.com/AndreasAugustin/actions-template-sync/assets/2818651/0ef9ef97-ef22-4afb-a902-51c896501520">

### Expected Behavior

PR should be created from created chore branch

### Current Behavior

See Description

### Possible Solution

unsure, theoretically `is_keep_branch_on_pr_cleanup: true` should work for me, but it is also has a bug (#528)

### Additional Information/Context

I am using `is_force_push_pr: true`. I don't really want to force push, I want to delete the branch first in all cases (which is essentially a force push, I suppose).

### Template sync version Version

2.2.0

**Comment by AndreasAugustin** [comment]
that is weird. Need to check it. Thanks for the report!

**Comment by AndreasAugustin** [comment]
@all-contributors please add @kanno41 for bug

**Comment by AndreasAugustin** [comment]
@kanno41 #534 should fix this issue. I need to test it.

You can try the solution with

```yaml
      - name: actions-template-sync
        # use here the related branch name
        uses: AndreasAugustin/actions-template-sync@#529
        with:
          source_repo_path: <owner/repo>
          upstream_branch: <target_branch> # defaults to main
          pr_labels: <label1>,<label2>[,...] # defaults to template_sync
          is_force_push_pr: true
          is_pr_cleanup: true
```
