### ISSUE TITLE
repository not found 

### ISSUE THREAD

**Issue by asehrawat24** [AndreasAugustin/actions-template-sync#578]
Hi, I am getting an error -  Token scopes: 'admin:org', 'admin:repo_hook', 'repo', 'workflow'
::info::Missing env variable 'UPSTREAM_BRANCH' setting to remote default main
remote: Repository not found.
fatal: repository 'https://github.my-company.com/github-actions/python-fastapi-template/' not found
fatal: Needed a single revision
Error: Process completed with exit code 128.
I followed the token instructions and access for actions is enabled too. 
but the repo does exist and can be even accessed through the url in the error

**Comment by AndreasAugustin** [comment]
Hi @asehrawat24 this is possibly related to the conversation within #557 
Possibly changing the action/download action to have flag `persist-credentials: false` helps.

```yaml
-
      name: Checkout
      uses: actions/checkout@v4
      with:
        # not sure yet why needed
        persist-credentials: false
```

Personally I do not understand the root cause yet (if this is the solution)
