### ISSUE TITLE
[Bug]: PR includes unexpected gh config files

### ISSUE THREAD

**Issue by cachitas** [AndreasAugustin/actions-template-sync#581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Running this action creates 2 unexpected files related with GitHub CLI config.

<img width="287" alt="Screenshot 2024-10-22 at 09 18 24" src="https://github.com/user-attachments/assets/ddc114f6-11a6-481d-87eb-5a1fae0ff348">

### Expected Behavior

These files should not be in the PR.

### Current Behavior

These files are not present in the template repository and by the looks of it, they may be created when running `gh` commands.
So far, I was not able to figure out if this is some side effect from this action of from `gh` CLI itself.

We are trying to sync two internal repos inside a organisation on a GitHub Enterprise instance.

My workflow definition (omitting some sensible fields):
```yaml
name: template-sync

on:
  schedule:
  - cron: "0 0 * * 1" # runs every monday at 00h00
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: <custom-org-runner>
    if: github.repository != '${{ vars.TEMPLATE_REPO_PATH }}' # Skip job if it's the template repo
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate token to read from source repo
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TEMPLATE_SYNC_APP_ID }}
          private_key: ${{ secrets.TEMPLATE_SYNC_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2.4.1
        with:
          hostname: <custom-ghe-hostname>
          github_token: ${{ steps.generate_token.outputs.token }}
          source_repo_path: ${{ vars.TEMPLATE_REPO_PATH }} 
          pr_title: "Sync with template repository"
          is_pr_cleanup: true
```

All other modifications are correctly gathered and present in the PR.

Could this be some side effect on running `gh` targeting our custom GHE host?
Could this be an issue originating from mixing in the GitHub app?

### Additional Information/Context

GitHub CLI 2.53.0

### Template sync version Version

2.4.1

**Comment by cachitas** [comment]
I am using a runner shared by my organisation. So nothing that I can really edit directly on my side.

I edited my workflow to output some more info. I added some steps to check env vars and list files in my working directory.

```yaml
- name: Debug env info
  run: |
    gh --version
    echo HOME=$HOME
    echo XDG_HOME_PATH=$XDG_HOME_PATH
    echo XDG_CONFIG_HOME=$XDG_CONFIG_HOME
    echo GH_PATH=$GH_PATH
    echo GH_CONFIG_DIR=$GH_CONFIG_DIR

- name: pwd
  run: pwd

- name: ls
  run: ls -la
```

And here is the output:

```
gh version 2.53.0 (2024-07-17)
https://github.com/cli/cli/releases/tag/v2.53.0
HOME=/home/runner
XDG_HOME_PATH=
XDG_CONFIG_HOME=
GH_PATH=
GH_CONFIG_DIR=
```

The working directory is `/home/runner/actions-runner/_work/<REPO_NAME>/<REPO_NAME>` and before running `actions-template-sync` contains:

```
drwxrwxr-x 2 runner runner 4096 Oct 23 09:55 .
drwxrwxr-x 3 runner runner 4096 Oct 23 09:55 ..
```

and after

```
drwxrwx--x 3 runner runner 4096 Oct 23 09:55 $HOME
drwxrwxr-x 5 runner runner 4096 Oct 23 09:55 .
drwxrwxr-x 3 runner runner 4096 Oct 23 09:55 ..
drwxrwxr-x 8 runner runner 4096 Oct 23 09:55 .git
drwxrwxr-x 3 runner runner 4096 Oct 23 09:55 .github
-rw-rw-r-- 1 runner runner   11 Oct 23 09:55 .templatesyncignore
-rw-rw-r-- 1 runner runner    0 Oct 23 09:55 <some _new_file_coming_from_template>
-rw-rw-r-- 1 runner runner   19 Oct 23 09:55 README.md
```

We can see the `$HOME` fir created there as reported above.

---

Having an empty `GH_CONFIG_DIR` led me to check its implications. From [GitHub CLI docs](https://cli.github.com/manual/gh_help_environment):

> `GH_CONFIG_DIR`: the directory where gh will store configuration files. If not specified, the default value will be one of the following paths (in order of precedence):
> - `$XDG_CONFIG_HOME/gh` (if `$XDG_CONFIG_HOME` is set),
> - `$AppData/GitHub CLI` (on Windows if $AppData is set), or
> - `$HOME/.config/gh`.

Since `XDG_CONFIG_HOME` is not set, it defaults to `$HOME/.config/gh`. Now why is this variable not being correctly expanded I have no idea. Any thoughts on this?
