### ISSUE TITLE
[Bug]: Sync does overwrite new changes

### ISSUE THREAD

**Issue by AppElent** [AndreasAugustin/actions-template-sync#588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I run this action, it creates a pull request with this change (among multiple):
![image](https://github.com/user-attachments/assets/bac9da6e-c55c-4810-be42-ac70eff91928)
Actually, this change has been made to the NEW repository (cloned from the template) and not on the old.
Is this expected functionality? If so, it is not suitable for template sync because then it overwrites all my changes.

### Expected Behavior

I was expecting to only check for changes on the source side. 

### Current Behavior

It overwrites new changes that I did with old values.

### Template sync version Version

v2

**Comment by AndreasAugustin** [comment]
Hi @AppElent and thankt for the report.
Is this the first time you run the sync? If it is the case then the issue is because both git histories are not merged (yet). Please just edit the commit within the PR branch.
All further runs should not touch your local changes with a exception:
if you change a file within both repositories (source and target) then obviously you will see changes in the PR.
This is per default on purpose so that devs can see that there are changes within the source. Just edit the PR with a new commit.
You are able to adjust this behaviour with the `git_remote_pull_params` parameter

**Comment by AndreasAugustin** [comment]
> Is there any better approach to solve this issue? That does not involve editing the commit message in the first PR?

hi @marques576 and thanks for the question. Unfortunately I did not understand the question. Can you please explain it in more details. E.g. an example from your discovery?

**Comment by AndreasAugustin** [comment]
> Repo A (github template repo) Repo B (generated from repo A using github template in the repo creation setup)
> 
> For example if I have repo A that is a github template repo and it contains the template-sync workflow. When I create Repo B from the template repo A, they are not in sync because there has never been a PR between both of them. And when I made changes and commit in repo B when the PR happens it will say the "correct" code is the code in repo A and the PR will basically revert my changes
> 
> My question is if there is away to sync the repos without having this behaviour in the first PR. And it not possible to trigger a PR in the repo B creation because there are no changes between the 2 repos.

The action is working with `git` . Therefore to somehow merge 2 different repositories you need at least one commit of the one repository into the other one. This is the first commit you mention. Then you will have the needed hashes in the other repository available.

(Unfortunately I still don't get the question about the commit message. )

The answer is: No, I am not aware of a way within git to make this work without a first commit because the repositories have unrelated histories. 

The good news is: after the first merge the needed history information is available in the target repository and it is easier for git to get the changes related to the history.

**Comment by AppElent** [comment]
> Hi [@AppElent](https://github.com/AppElent) and thankt for the report. Is this the first time you run the sync? If it is the case then the issue is because both git histories are not merged (yet). Please just edit the commit within the PR branch. All further runs should not touch your local changes with a exception: if you change a file within both repositories (source and target) then obviously you will see changes in the PR. This is per default on purpose so that devs can see that there are changes within the source. Just edit the PR with a new commit. You are able to adjust this behaviour with the `git_remote_pull_params` parameter

Hi, thanks for the feedback. I dont really understand it, can you explain in more detail how this would work? In other words, what does "just edit the commit within the PR branch" mean?
Can you elaborate on the steps?
1. create template repo (done)
2. create child repo (done)
3. first sync run......... (what do I need to do?)

**Comment by AndreasAugustin** [comment]
> I didnt edit the commit but I did new commits, how do I edit commit?

you can amend to a commit https://www.atlassian.com/git/tutorials/rewriting-history
but actually that won't work. Do you have by any chance a link to your repository?

**Comment by AndreasAugustin** [comment]
@AppElent another thought. You can also use the `.templatesyncignore` file to ignore files for changes.
Reading your statement related a hour long merge issue possibly this is also a solution for you https://github.com/AndreasAugustin/actions-template-sync?tab=readme-ov-file#ignore-files

**Comment by AndreasAugustin** [comment]
Hi @AppElent did you try the suggestions? Do they work now?

**Comment by AppElent** [comment]
Hi! 
Thanks for the reply. I am using templatesyncignore, this works for some files (that dont change) but not for others. 
My template repo: https://github.com/AppElent/template-vite-ts-react-app
Downstream repo: https://github.com/[AppElent/test123](https://github.com/AppElent/test123)

I am pushing directly to main on both repo's

**Comment by AndreasAugustin** [comment]
> Hi! Thanks for the reply. I am using templatesyncignore, this works for some files (that dont change) but not for others. My template repo: https://github.com/AppElent/template-vite-ts-react-app Downstream repo: [https://github.com/[AppElent/test123](https://github.com/AppElent/test123)](https://github.com/%5BAppElent/test123%5D(https://github.com/AppElent/test123))
> 
> I am pushing directly to main on both repo's

Hi @AppElent thanks for the links but I need to admit. I don't get it.
I only found one PR related to the repo sync https://github.com/AppElent/test123/pull/6 with no changes.
And if you check the logs of the action it states that nothing needs to be done.

https://github.com/AppElent/test123/actions/runs/12868331156/job/35874777930

**Comment by nneto** [comment]
That is my issue as well. I don't know if I'm using the action incorrectly or if this is the expected outcome.
The action made a [PR](https://github.com/nneto/my-finpilot/pull/3/commits) undoing all the changes I made in my repository. I made a new commit in the PR branch, as @AndreasAugustin told on the first reply, reapplying all the changes made before in my repository and merged the PR.
But when the action was run again and made the next [PR](https://github.com/nneto/my-finpilot/pull/4), again it just overwrites all changes in my repository.
Is that expected? That the action will always try to "reset" the repository to the same "state" as the template?

**Comment by mzglinski** [comment]
Encountered the same problem. Solved it by removing `--squash` and adding the `--no-ff --no-edit` flags to `git_remote_pull_params`. This, however, broke the `.templatesyncignore` functionality, and I wanted it, so I had to implement the logic outside the action. Here is the final result.


```yaml
name: Template Sync

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  sync:
    name: Sync template changes
    if: ${{ github.ref_name == 'main' || github.ref_name == 'master' }}
    runs-on: arc-runner
    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          if ! command -v gh &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y gh
          fi

      - uses: AndreasAugustin/actions-template-sync@v2
        name: Template sync — pull
        with:
          steps: 'prechecks,pull'
          source_gh_token: ${{ steps.app-token.outputs.token }}
          target_gh_token: ${{ steps.app-token.outputs.token }}
          source_repo_path: 'org/template-repo'
          git_remote_pull_params: --allow-unrelated-histories --no-ff --no-edit --strategy=recursive -X theirs
          is_pr_cleanup: true
          pr_branch_name_prefix: chore/template-sync

      - name: Restore ignored files
        id: restore
        run: |
          CURRENT_BRANCH=$(git branch --show-current)
          if [[ "$CURRENT_BRANCH" != chore/template-sync* ]]; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "⏭️  Not on sync branch ($CURRENT_BRANCH) — skipping."
            exit 0
          fi

          if [ ! -f .templatesyncignore ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          AMENDED=false

          while IFS= read -r pattern || [ -n "$pattern" ]; do
            [[ "$pattern" =~ ^[[:space:]]*$ ]]  && continue
            [[ "$pattern" =~ ^[[:space:]]*#  ]] && continue
            [[ "$pattern" == !*               ]] && continue

            mapfile -t matched < <(git ls-files -- "$pattern" 2>/dev/null)

            if [ ${#matched[@]} -gt 0 ]; then
              echo "  Restoring ${#matched[@]} file(s) for pattern: $pattern"
              git restore --source=HEAD^1 -- "${matched[@]}"
              AMENDED=true
            fi
          done < .templatesyncignore

          if [ "$AMENDED" = true ]; then
            git add -A
            if ! git diff --cached --quiet; then
              git commit --amend --no-edit
              echo "Merge commit amended with restored ignored files."
            fi
          fi

          # Check if sync branch has any real changes vs the default branch
          DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
          CHANGED=$(git diff "origin/${DEFAULT_BRANCH}...HEAD" --name-only | wc -l | tr -d ' ')

          echo "changed=${CHANGED}" >> "$GITHUB_OUTPUT"
          if [ "$CHANGED" -gt 0 ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "✅ ${CHANGED} file(s) changed — PR will be created."
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "⏭️  Only ignored files changed — skipping PR."
          fi

      - name: Template sync — push and PR
        if: steps.restore.outputs.has_changes == 'true'
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          steps: 'push,pr'
          source_gh_token: ${{ steps.app-token.outputs.token }}
          target_gh_token: ${{ steps.app-token.outputs.token }}
          source_repo_path: 'org/template-repo'
          is_pr_cleanup: true
          pr_labels: template-sync
          pr_title: 'chore(template): upstream merge template repository'
          pr_branch_name_prefix: chore/template-sync
          pr_body: |
            ## ⛔ Merge this PR with "Create a merge commit" only
            Do **not** use "Squash and merge" or "Rebase and merge".
            Both rewrite history and destroy the sync point between this repo and the template.
            Future syncs will re-propose all changes from scratch and produce unnecessary conflicts.

            ### Resolving conflicts
            If this PR has conflicts or you need to adjust any auto-resolved changes:
            1. Check out this branch locally
            2. Make your changes
            3. **Amend the merge commit** (`git commit --amend --no-edit`) instead of creating a new commit
            4. Force-push the branch (`git push --force-with-lease`)

            This keeps the PR as a single merge commit, preserving a clean sync point.

            ---

            Synced with `${SOURCE_REPO}` at `${TEMPLATE_GIT_HASH}`.
```
