### ISSUE TITLE
[Bug]: 2.5.0 break existing behavior

### ISSUE THREAD

**Issue by ahanoff** [AndreasAugustin/actions-template-sync#608]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Release https://github.com/AndreasAugustin/actions-template-sync/releases/tag/v2.5.0 removes github-token input, as result all my sync workflows require individual update to use `source_gh_token` which kills the purpose of having this sync worklfow

### Expected Behavior

Expected to v2 work without breaking changes

### Current Behavior

```sh
Warning: Input 'github_token' has been deprecated with message: please use source_gh_token instead to have a declarative name
Run AndreasAugustin/actions-template-sync@v2
Run /home/runner/work/_actions/AndreasAugustin/actions-template-sync/v2/src/entrypoint.sh
git init
ssh setup
::info::prechecks passed
::info::current git hash: 20171d6c63c602f363cefd3842eca566c799335e
::info::variables done
::info::no steps provided. Default is to execute all.
::info::prechecks
prechecks
::info::checkout branch and pull
checkout branch and pull
login target github
  ::info::target server url: github.com
  ::info::logging out of the target if logged in
  no accounts matched that criteria
  ::info::login to the target git repository
  The value of the GITHUB_TOKEN environment variable is being used for authentication.
  To have GitHub CLI store credentials instead, first clear the value from the environment.

```

### Steps To Reproduce

Workflow file

```yml
name: Synchronize with upstream template
on:
  # cronjob trigger At 00:00 on day-of-month 1 in every 2nd month.
  schedule:
    - cron: '0 0 1 */2 *' # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
  # manual trigger
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_PAT }} # PAT with permissions to modify github actions workflows

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ github.token }}
          upstream_branch: main # defaults to main
          source_repo_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # github token from context not able to pull source repository in another private repo. We use private key to access source repo via SSH protocol
          pr_branch_name_prefix: fix/template_sync
          pr_title: 'fix: sync with parent template'
          pr_labels: 'enhancement'
```

### Possible Solution

Either make it non-breaking change, or bump major version instead to v3

### Template sync version Version

AndreasAugustin/actions-template-sync@v2

**Comment by ahanoff** [comment]
> https://github.com/AndreasAugustin/actions-template-sync/actions/runs/13179889870/job/36787779385

even unit-tests are failing, why PR tests didn't catch this though?

**Comment by ahanoff** [comment]
```2025-02-10T06:44:49.4971254Z ##[group]login target github
2025-02-10T06:44:49.4973242Z ::info::target server url: github.com
2025-02-10T06:44:49.4975188Z ::info::logging out of the target if logged in
2025-02-10T06:44:49.6986544Z no accounts matched that criteria
2025-02-10T06:44:49.7009074Z ##[debug]not logged in
2025-02-10T06:44:49.7013455Z ::info::login to the target git repository
2025-02-10T06:44:49.7556567Z The value of the GITHUB_TOKEN environment variable is being used for authentication.
2025-02-10T06:44:49.7561623Z To have GitHub CLI store credentials instead, first clear the value from the environment.
2025-02-10T06:44:49.7585074Z ##[error]Process completed with exit code 1.
```

hi @AndreasAugustin , I've re-run workflow with debug enabled.

Attached logs from workflow. Obfuscated some private details, but the logs messages are intact

[github-actions-sync.log](https://github.com/user-attachments/files/18729335/github-actions-sync.log)

**Comment by AndreasAugustin** [comment]
Hi @ahanoff and thanks for sharing the details. Will look into it (hopefully tonight) . 
Just one question: why are you using a PAT for the checkout action? Just want to understand some different use cases.

Remark:
This could be the reason for the current issue. 
There is a option to log out again whithin the checkout action (can share more details later).
This is currently just an idea but theoretically it is possible (also looking into your error message). The context of steps are the same on one runner so credentials are shared.
It worked in the past because there was no special login operation related the target, but actually there was a bug in the old implementation.

If this is the reason currently I do not have a solution available but will think about it.

**Comment by ahanoff** [comment]
>  Just one question: why are you using a PAT for the checkout action? Just want to understand some different use cases.

I'm using [Github template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository#about-template-repositories) repository to centrally manage all child repository workflows.

Custom PAT needs to write new changes in `.github/workflows` directory after sync

**Comment by AndreasAugustin** [comment]
> > Just one question: why are you using a PAT for the checkout action? Just want to understand some different use cases.
> 
> I'm using [Github template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository#about-template-repositories) repository to centrally manage all child repository workflows.
> 
> Custom PAT needs to write new changes in `.github/workflows` directory after sync

thanks for the clarification. Totally valid use case and I totally forgot about the need for PAT to modify the workflow files.

**Remark**
Actually this is not an issue with the mentioned `warning` in the statement. The `github_token` input is still working.
But there has been a change for the `target_github_token`. It implicitly was using the `GITHUB_TOKEN` env variable which was set by the checkout workflow. This was actually breaking other use cases (and was a bug).

For a fast workaround on your side using smth like

```yaml

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ github.token }}
          upstream_branch: main # defaults to main
          source_repo_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # github token from context not able to pull source repository in another private repo. We use private key to access source repo via SSH protocol
          pr_branch_name_prefix: fix/template_sync
          pr_title: 'fix: sync with parent template'
          pr_labels: 'enhancement'
         target_gh_token: ${{ secrets.WORKFLOW_PAT }}  # use here the token
```

should do the trick.
You can remove that part from the checkout step and use the workflow token (optional).

This issue is most likely not that easy to solve. Need to think about it.

**Comment by ahanoff** [comment]
> For a fast workaround on your side using smth like (yes currently breaking but not sure about a fast solution)

I will try and update if it's working. Problem is I have like ~50 repos to update 😄

**Comment by AndreasAugustin** [comment]
> > For a fast workaround on your side using smth like (yes currently breaking but not sure about a fast solution)
> 
> I will try and update if it's working. Problem is I have like ~50 repos to update 😄

totally understandable. But unfortunately I cannot give an ETA. But I try to solve it within this week.

**Comment by AndreasAugustin** [comment]
> > For a fast workaround on your side using smth like (yes currently breaking but not sure about a fast solution)
> 
> I will try and update if it's working. Problem is I have like ~50 repos to update 😄

i @ahanoff did you have the chance to test the way with the `target_gh_token` variable? Feedback highly appreciated.

**Remark**
I am still trying to find a way to solve the issue but I do not have nice ideas. The issue is that the former implementation was buggy and it is not easy to get the right token within the current workflow. The gh cli is not super nice in the usage of different tokens. Possibly it even makes sense to change the config path to have a clean environment within the action.
But this will most likely break other things...

**Comment by ahanoff** [comment]
hi @AndreasAugustin, didn't try it yet

> I am still trying to find a way to solve the issue but I do not have nice ideas.

Would it be issue to retract 2.5.0 and release it as 3.x instead?

**Comment by ahanoff** [comment]
```yaml
with:
  source_gh_token: ${{ github.token }}
  target_gh_token: ${{ secrets.WORKFLOW_PAT }}
```

with this configuration works as expected

**Comment by alexvanderberkel** [comment]
@ahanoff have you tried using a GitHub app instead of a PAT?

**Comment by ahanoff** [comment]
> [@ahanoff](https://github.com/ahanoff) have you tried using a GitHub app instead of a PAT?

hi @alexvanderberkel, no, I haven't and not considering it

**Comment by AndreasAugustin** [comment]
> with:
>   source_gh_token: ${{ github.token }}
>   target_gh_token: ${{ secrets.WORKFLOW_PAT }}
> with this configuration works as expected

thanks for the test.

> 
> Would it be issue to retract 2.5.0 and release it as 3.x instead?

Thought about this possibility but no. This is currently a bug fix and should be treated like one related to semver.

Also really tried to find a solution. Actually I have a workaround but not super sure if it is working (and actually I don't like the solution).
Please test the following branch:

```yaml
- name: actions-template-sync
        # use here the branch <fix/#608> instead of the v2
        uses: AndreasAugustin/actions-template-sync@fix/#608
        with:
```

in one of your cases and share the result. Thanks.


**Remarks:**

- The plan with #586 is to have the possibility to have one repo where you run the action and update all related other repositories. The implementation should be straight forward. But currently not possible to give an ETA. But this should make it easier to handle the updates 
- a simple script doing your updates could look like the following: (not tested, no warranty :) )

```bash
#!/usr/bin/env bash

# within the script a prerequisite is to have locally all repos checked out.
# also you have the right template sync github yaml definition in the parent dir of the repos
# gh cli need to be available and you need to be logged in
declare -a arr=("dir1" "dir2" "dir3")

for i in "${arr[@]}"
do
   echo "updating $i"
   # change into the repo dir
   pushd $i ;
   git checkout main
   git pull
   git checkout -b chore/update_template_sync
   cp <path_to_template_sync_ignore_file> .github/workflows/<file_name>
   git add .github/workflows/<file_name>
   git commit -S -s -m "chore: update template sync file"
   git push
   gh pr create --title <add_title> --body <add_body>
  popd
done

```

This will at least create a PR with the needed updates. You could also push already to the main, but not recommended.

**Further remark**
> [@ahanoff](https://github.com/ahanoff) have you tried using a GitHub app instead of a PAT?
a bit off topic but possibly worth to share. Most likely this won't solve the current issue but in most cases worth to consider using a github app over a PAT. A PAT always has a user context and the action has more a robot context.

**Comment by ahanoff** [comment]
>  Please test the following branch (theoretically it should work for your case):

tested on my original workflow and it works @AndreasAugustin 

```yml
- name: actions-template-sync
  uses: AndreasAugustin/actions-template-sync@fix/#608
  with:
     github_token: ${{ github.token }}
...
```

> and actually I don't like the solution). https://github.com/AndreasAugustin/actions-template-sync/pull/614

@AndreasAugustin up to you, I just need clarity whether actions will be fixed or I will have to proceed with fixes myself. Thanks for help anyway!
